### ISSUE TITLE
Slugbuilder broken on empty default process types

### ISSUE THREAD

**Issue by Joshua-Anderson** [deis/slugbuilder#103]
Heroku's java buildpack's `bin/release` script used to return:

```

---
addons:
  - heroku-postgresql
```

Now it returns:

```

---
```

causing the error 

```
-e:1:in `<main>': undefined method `[]' for nil:NilClass (NoMethodError)
```

in the ruby script [here](https://github.com/deis/slugbuilder/blob/master/rootfs/builder/build.sh#L169).

**Comment by mboersma** [comment]
Nice sleuthing!
