### ISSUE TITLE
download official mc client when there's an official release

### ISSUE THREAD

**Issue by arschles** [deis/slugbuilder#13]
[This comment](https://github.com/deis/minio/issues/1#issuecomment-162118057) indicates that official releases will be ready later this month. When the release is ready, `mc` should be downloaded on `docker build` instead of checked into this repo.

Relates to https://github.com/deis/minio/issues/30 and https://github.com/deis/builder/issues/46.

**Comment by arschles** [comment]
Ref https://github.com/minio/minio/issues/1041

**Comment by kmala** [comment]
closing this as we are no longer using the minio client.
