### ISSUE TITLE
USN-3438-1: Git vulnerability

### ISSUE THREAD

**Issue by Bregor** [deis/slugbuilder#144]
Package `git-core` should be upgraded in `quay.io/deis/slugbuilder` image due to [USN-3438-1](https://usn.ubuntu.com/usn/usn-3438-1/)

**Comment by bacongobbler** [comment]
See https://github.com/deis/slugrunner/issues/68#issuecomment-334510669. I've also gone ahead and performed the same fix for the builder so we're good on all fronts.

**Comment by bacongobbler** [comment]
re-opening due to https://github.com/deis/slugrunner/issues/68#issuecomment-335589286 (thanks @stuszynski for the heads up).

**Comment by bacongobbler** [comment]
done.
