### ISSUE TITLE
Check the object storage endpoint to determine which signature version to use

### ISSUE THREAD

**Issue by arschles** [deis/slugbuilder#31]
S3 and Minio should use the S3 V4 signature version, and Google Cloud Storage in compatibility mode should use the V2 version.

Ref https://github.com/deis/builder/issues/222

**Comment by smothiki** [comment]
respective PR got merged

**Comment by arschles** [comment]
I believe it was https://github.com/deis/slugbuilder/issues/33, right @smothiki?

**Comment by smothiki** [comment]
Yes

**Comment by arschles** [comment]
Thanks
