### ISSUE TITLE
Use deis-objectstorage-secret.yaml to get S3 credentials

### ISSUE THREAD

**Issue by smothiki** [deis/slugbuilder#32]
[Object storage docs](https://github.com/deis/workflow/blob/master/src/installing-workflow/configuring-object-storage.md#credentials) should also be upgraded when this work is done.

Related: deis/workflow#61

**Comment by arschles** [comment]
@smothiki can we move this to RC? It doesn't seem necessary to get this in for beta, given that we've decided to keep builder on the 'minio-user' secret

**Comment by bacongobbler** [comment]
removing from beta milestone

**Comment by arschles** [comment]
[Object storage docs](https://github.com/deis/workflow/blob/master/src/installing-workflow/configuring-object-storage.md#credentials) should also be upgraded when this work is done.

**Comment by arschles** [comment]
Also related: https://github.com/deis/builder/issues/224 and https://github.com/deis/slugrunner/issues/18

**Comment by kmala** [comment]
fixed in #41
