### ISSUE TITLE
Add information on how to configure slugbuilder for standalone usage into the README

### ISSUE THREAD

**Issue by arschles** [deis/slugbuilder#39]
Notes to make, under the `About` section:
- What to set the `TAR_URL` env var to
- What to set the `put_url` env var to
- How to configure the object store secret (or link to the object store docs)

This issue was created in response to https://github.com/deis/slugbuilder/pull/38#discussion_r56401234

cc/ @smothiki

**Comment by bacongobbler** [comment]
I've currently been playing around with slugbuilder in a standalone context for #97 so I can write some docs around this.

**Comment by bacongobbler** [comment]
this is documented in the builder's README. Closing!
