### ISSUE TITLE
fix(Dockerfile): store mc binary and download on docker build

### ISSUE THREAD

**Issue by arschles** [deis/slugbuilder#4]
they don't have 'official' releases now, but it should be good enough to download from dl.minio.io for now

**Comment by arschles** [comment]
related to https://github.com/deis/builder/issues/11 and https://github.com/deis/dockerbuilder/issues/2

**Comment by arschles** [comment]
binary stored at https://storage.googleapis.com/alpine-binaries/mc

**Comment by smothiki** [comment]
Slugbuilder and Slugrunner are not alpine based images. I have built MC from repository and added here manually.

**Comment by arschles** [comment]
thanks for reminding. I've removed the 'alpine' part from the title and I think this issue still stands. can we not just download them from dl.minio.com? I've done so at https://github.com/arschles/slugbuilder/blob/minio/rootfs/Dockerfile#L7 and it works fine

**Comment by smothiki** [comment]
+1
