### ISSUE TITLE
Error when compiling a GO app

### ISSUE THREAD

**Issue by kmala** [deis/slugbuilder#50]
This error is intermittently occurring when trying to build a go app ([example go](https://github.com/deis/example-go)) .
`remote: + echo '----->' Checking Godeps/Godeps.json file.        
       remote: -----> Checking Godeps/Godeps.json file.        
      remote: + read line        
       remote:        
    remote: gzip: stdin: unexpected end of file        
      remote: tar: Unexpected EOF in archive        
      remote: tar: Unexpected EOF in archive        
      remote: tar: Error is not recoverable: exiting now`
This is happening because the go slug is not properly downloading the go (https://github.com/heroku/heroku-buildpack-go/blob/master/bin/compile#L160)

**Comment by arschles** [comment]
Thanks for filing this issue. I think it may be wise for us store these slugs on S3 (or equivalent), and allow their location to be customized. Currently we rely on GitHub for serve them.

I've moved this to RC1

**Comment by kmala** [comment]
The issue is with downloading the go binary (https://github.com/heroku/heroku-buildpack-go/blob/master/bin/compile#L22) and its happening in the buildpacks code  which we might not have full control.

**Comment by mboersma** [comment]
This should be fixed--at least as much as is reasonable--by v32 of [heroku-buildpack-go](https://github.com/heroku/heroku-buildpack-go/releases/tag/v32) which is in slugbuilder.
