### ISSUE TITLE
Proposal: investigate a way to test all buildpacks

### ISSUE THREAD

**Issue by arschles** [deis/slugbuilder#63]
Can we add some unit or functional tests in this repo (to be run in CI) that run through all supported buildpacks? This would give us _more_ confidence in buildpack upgrades

**Comment by arschles** [comment]
Punting this to RC as the investigation hasn't started yet.

**Comment by arschles** [comment]
@mboersma I believe this is done, yea?

**Comment by mboersma** [comment]
@arschles it is accomplished in the e2e tests, but this originally described trying to test all buildpacks in a unit or functional test just for slugbuilder. That sounds difficult to me, and redundant. I'll close this.
